### ISSUE TITLE
The computed property "xx" is already defined in data.

### ISSUE THREAD

**Issue by bingxueyinlian** [FranckFreiburger/vue3-sfc-loader#129]
**Describe the bug**
When the data variable in the remote component has the same name as the computed property of the host page with mixin, an error is reported,like 'The computed property "aa" is already defined in data.'
![image](https://user-images.githubusercontent.com/1235035/162945178-bc2a013d-196b-44dc-a708-985cfce9bb50.png)

**To Reproduce**

remote component 
```
<script>
export default {
  data() {
    return {
      aa: '',
    };
  },
};
</script>
```
host page with mixin
mixin.js
```
let mixin = {
  computed: {
    aa() {
      return '123';
    },
  },
};
export default mixin;
```
main.js
```
import mixin from '@/mixin.js';
Vue.mixin(mixin);
```
**Expected behavior**
The data variable definition of the remote component is independent of the computed property of the host page with mixin.

**Versions**
 - Browser (name & version): Chrome  100.0.4896.75
 - vue3-sfc-loader: 0.8.4
 - vue：2.6.12

**Comment by FranckFreiburger** [comment]
Hello bingxueyinlian, this issue is not related to vue3-sfc-loader.
see [Vue SFC Playground](https://play.vuejs.org/#eNp9UbFOwzAQ/RXLS0CqUkG3EJAAdYABELBhBiu5BhfHtuxziVTl37GdJs1QdbF9797dvXfe03tj8p0HWtDSVVYYvGOKKQlIWtEJRW7JnilCKt0aj1AXQ0gI5xeX45sQC+itItnVdXYzYP0i3vHsA8IUdEZbJDVsuJc4VKYJrvhK93cqqDnOGh/aTmM4L0iWJWLonSYdJ5TLmYESoTWSI4SoXM4CuqDoKq02osm3TqtgPLVnNFoUEuyrQaGVY3TyyiiXUv89Jwyth4OCUPMD1e8JfOu6iDH6ZsGB3QGjUw65bQCH9PrjBbrwnpKtrr0M7DPJd3Ba+qhxoD14VQfZM15S+9TGhQvVfLp1h6DcaCoKHTcX2eH3H89YP8pd5atUFxZO+3+pV7gP)
